# This was generated by `cabal2nix --shell .`
# Also see: https://robertwpearce.com/hakyll-pt-6-pure-builds-with-nix.html
#
{ nixpkgs ? import <nixpkgs> {}, compiler ? "default", doBenchmark ? false }:

let

  # TODO Hakyll is marked as broken in NixOS 20.09 so for now use 20.03's.
  #inherit (nixpkgs) pkgs;
  # pkgs = import (builtins.fetchGit {
  #   # Descriptive name to make the store path easier to identify
  #   name = "nixos-20.03";
  #   url = "https://github.com/nixos/nixpkgs-channels/";
  #   ref = "refs/heads/nixpkgs-20.03-darwin";
  #   rev = "1975b8687474764c157e6a220fdcad2c5dc348a1";
  # }) {};

  pkgs = nixpkgs;
  myPkg = pkgs.haskellPackages.hakyll;

  f = { mkDerivation, base, hakyll, pandoc, stdenv }:
      mkDerivation {
        pname = "photonsphere";
        version = "0.1.0.0";
        src = ./.;
        isLibrary = false;
        isExecutable = true;
        executableHaskellDepends = [ base hakyll pandoc ];
        license = "unknown";
        hydraPlatforms = stdenv.lib.platforms.none;
      };

  haskellPackages = if compiler == "default"
                       then pkgs.haskellPackages
                       else pkgs.haskell.packages.${compiler};

  variant = if doBenchmark then pkgs.haskell.lib.doBenchmark else pkgs.lib.id;

  drv = variant (haskellPackages.callPackage f {});

in

  if pkgs.lib.inNixShell then drv.env else drv
