* Privacy policy
This privacy policy explains how personal information is processed when this website is used.

* Personal information
When using this website, the only personal information that is
collected is the information that is sent automatically to the
webserver by your browser. This is done via the **log files** that the
website hosting provider maintains. If you want to visit this website,
the webserver collects and stores the following data, which are
required for technical reasons to display the website and to guarantee
stability and safety (legal basis in the EU is Article 6(1f) GDPR):

- o IP-address
- o Date and time of the request
- o Difference between time zone and Greenwich Mean Time (GMT)
- o Content of the request (specific page)
- o Access status/HTTP-statuscode
- o Website from which the request was received
- o Browser, language and version of the browser software
- o Operating system and interface

The information in the log files serves only the above mentioned purpose.

* What are cookies?
Cookies are small text files, which are placed on your computer to e.g. collect standard Internet log information and visitor behaviour information.

* What cookies are used?
This website uses no cookies.
