----
title: Building Photivo under Debian Linux
modified: 2015-01-30
meta_description: 
tags: Computer, GUI, Linux, Software, Shell Script, Photography
----

[[http://photivo.org/][Photivo]] is a free and open source (GPL3) photo processor. It handles
your RAW files as well as your bitmap files (TIFF, JPEG, BMP, PNG and
many more) in a non-destructive 16 bit processing pipe with gimp
workflow integration and batch mode.

* Linux build instructions
     :PROPERTIES:
     :CUSTOM_ID: linux-build-instructions
     :END:

The instructions to build Photivo under Linux can be found on the
Photivo site, under [[http://photivo.org/download/linux][Photivo -> Download and Setup -> Linux]].

The Debian Linux (Jessie) specific parts of these instructions are
given in the following sections.

* Packages
     :PROPERTIES:
     :CUSTOM_ID: packages
     :END:

The command to install the required packages for Debian is as follows:

#+BEGIN_SRC sh
sudo apt-get install gcc g++ ccache qt4-qmake mercurial libqt4-dev libjpeg62-turbo-dev:amd64 libexiv2-dev liblensfun-dev libfftw3-dev libpng12-dev libtiff5 liblcms2-dev libgimp2.0-dev libgraphicsmagick++3
#+END_SRC

* Lcms2
     :PROPERTIES:
     :CUSTOM_ID: lcms2
     :END:

On my system the Debian package for =lcms2= works fine. This was
installed already (above under the =Packages= section).

* GraphicsMagick 16 bit
     :PROPERTIES:
     :CUSTOM_ID: graphicsmagick-16-bit
     :END:

This needs to be downloaded and built as instructed. But do change the
prefix to =/usr/local=, so the commands to use are as follows:

#+BEGIN_SRC sh
./configure --prefix=/usr/local --with-quantum-depth=16 --enable-shared --without-lcms
make -j4
sudo make install

#+END_SRC

* Liquid rescale (liblqr)
     :PROPERTIES:
     :CUSTOM_ID: liquid_rescale_liblqr
     :END:

This needs to be downloaded and built as instructed. But do change the
prefix to =/usr/local=, so the commands to use are as follows:

#+BEGIN_SRC sh
./configure --prefix=/usr/local
 make -j4
 sudo make install
#+END_SRC

* Lensfun header files
     :PROPERTIES:
     :CUSTOM_ID: lensfun-header-files
     :END:

Because the =lensfun- header files are located in a different location
than expected by Photivo an environment variable needs to be set as
follows:

#+BEGIN_SRC sh
INCLUDEPATHS="/usr/include/lensfun"
export INCLUDEPATHS
#+END_SRC

* Building Photivo
     :PROPERTIES:
     :CUSTOM_ID: building-photivo
     :END:

With the =INCLUDEPATHS= environment variable set as instructed above the
instructions for building Photivo can be followed. But do change the
prefix to =/usr/local=, so the commands to use are as follows:

#+BEGIN_SRC sh
hg clone https://photivo.googlecode.com/hg/ photivo
cd photivo
hg update default
qmake photivo.pro PREFIX=/usr/local
make -j4
sudo make install
#+END_SRC
