----
title: Specific compiler switches per package in Gentoo
modified: 2015-01-03
meta_description: 
tags: Computer, Software, Linux, Gentoo
----

To configure specific compiler switches per package in Gentoo use
these instructions.

(.more.)

* Modifying environmental variables per package
     :PROPERTIES:
     :CUSTOM_ID: modifying-environmental-variables-per-package
     :END:

The =package.env= file can be used to modify environmental variables
per package. See [[http://wiki.gentoo.org/wiki//etc/portage/env][/etc/portage/env]] in the Gentoo Wiki for details.

* Conflicting compiler switches
     :PROPERTIES:
     :CUSTOM_ID: conflicting-compiler-switches
     :END:

In =make.conf= one typically specifies compiler switches that are
selected to optimize for one's specific machine. But some packages
(e.g. /www-client/chromium/) have their own build system, which can
result in conflicting compiler switches.

* Disabling compiler switches per package
     :PROPERTIES:
     :CUSTOM_ID: disabling-compiler-switches-per-package
     :END:

This can be done via =package.env= and helper files in the =env=
subdirectory. For example, if =/etc/portage/make.conf= specifies the
following section:

#+BEGIN_SRC sh
CFLAGS="-O2 -march=native -pipe" CXXFLAGS="${CFLAGS}"
#+END_SRC

then in =/etc/portage/package.env= the following section will select
specific flags for the =www-client/chromium= package:

#+BEGIN_SRC sh
www-client/chromium cflags-no-optimization
#+END_SRC

and in the =/etc/portage/env/cflags-no-optimization= file holds the
specific environmental variable:

#+BEGIN_SRC sh
# No optimization # CFLAGS="-march=native -pipe"
CXXFLAGS="${CFLAGS}"
#+END_SRC

This prevents that the =-O2= compiler switch that is specified in
=make.conf= is used for the =www-client/chromium= package.
