----
title: Suspend/Resume problems Docker containers
modified: 2016-09-13
meta_description: 
tags: Computer, Software, GUI, KDE, Linux, Shell Script, Docker
----

#+OPTIONS: ^:nil

Once upon a time, while using Debian I had a problem with Docker containers and suspend/resume.

* Docker resume/thaw problems?
    :PROPERTIES:
    :CUSTOM_ID: docker-resumethaw-problems
    :END:

When you use [[https://www.docker.com/][Docker]] containers on your development system and
experience problems after a resume from a suspend (or a thaw from a
hibernate). On my Debian Stable KDE system --after a resume of my
[[https://www.mongodb.com/][MongoDB]] and [[http://wildfly.org/][WildFly]] containers-- the screensaver did not ask for a
password and the computer did not respond to mouse and keyboard.

* Fix via pm-utils script
    :PROPERTIES:
    :CUSTOM_ID: fix-via-pm-utils-script
    :END:

A pm-utils script can be added to pause all running Docker containers
on suspend /hibernate and unpause them on resume/thaw. Create a
file =/usr/lib/pm-utils/sleep.d/00docker= with following content:

#+BEGIN_SRC sh
#!/bin/sh
. "${PM_FUNCTIONS}"
command_exists docker || exit $NA
# Pause all running docker containers on suspend|hibernate and unpause on resume|thaw.
case $1 in
    suspend|hibernate) docker pause $(docker ps -q) ;;
    resume|thaw)       docker unpause $(docker ps -q) ;;
    *) exit $NA ;;
esac
exit 0
#+END_SRC
