----
title:  Ferret
modified: 2016-06-11
meta_description: 
tags: Computer, Software, C++, Embedded, Real-Time, Functional, Clojure
----

#+OPTIONS: ^:nil

Ferret is a free software Clojure implementation, it compiles a
restricted subset of the Clojure language to self contained /ISO
C++11/ which allows for the use of Clojure in real time embedded
control systems -- [[https://nakkaya.com/2016/06/10/ferret-a-hard-real-time-clojure-for-lisp-machines/][Ferret]] by *Nurullah Akkaya*)

(.more.)

* From its documentation

Ferret does not depend on any external dependencies (Including the C++
Standard Library). Unit tests are run on Mac OS X and Linux, any
operating system with a C++11 compiler is supported. When running on a
microcontroller ferret will check if it is a supported platform during
compile time and enable hardware specific features. (Currently only
UART is hardware specific.) If running on an unknown hardware it will
run in safe mode (UART disabled.). Everything else is supported in
safe mode. Like operating system support any embedded system with a
C++11 compiler is supported. There's a list of currently supported
microcontrollers in the [[http://ferret-lang.org/][Ferret documentation]] under Hardware /
Operating System Support.
