----
title: Julia programming language
modified: 2018-03-23
meta_description: 
tags: Computer, Software, Numerical, Machine Learning, AI, Data Science, Scientific Computing, Julia
----

A high-level, high-performance dynamic programming language for
numerical computing. It provides a sophisticated compiler, distributed
parallel execution, numerical accuracy, and an extensive mathematical
function library. -- [[https://github.com/JuliaLang/julia][Julia]] (by *[[https://julialang.org/][JuliaLang]]*).

(.more.)

* Julia
    :PROPERTIES:
    :CUSTOM_ID: julia
    :END:

Julia is the fastest high performance open source computing language
for data, analytics, algorithmic trading, machine learning, artificial
intelligence, and many other domains. Julia solves the two language
problem by combining the ease of use of Python and R with the speed of
C++. Julia provides parallel computing capabilities out of the box and
unlimited scalability with minimal effort.

Julia's Base library, largely written in Julia itself, also integrates
mature, best-of-breed open source C and Fortran libraries for linear
algebra, random number generation, signal processing, and string
processing.

* Multiple dispatch
    :PROPERTIES:
    :CUSTOM_ID: multiple-dispatch
    :END:

Julia programs are organized around multiple dispatch, which allows
built-in and user-defined functions to be overloaded for different
combinations of argument types.

* Metaprogramming
    :PROPERTIES:
    :CUSTOM_ID: metaprogramming
    :END:

The strongest legacy of Lisp in the Julia language is its
metaprogramming support. Like Lisp, Julia represents its own code as a
data structure of the language itself. Since code is represented by
objects that can be created and manipulated from within the language,
it is possible for a program to transform and generate its own code.
This allows sophisticated code generation without extra build steps,
and also allows true Lisp-style macros operating at the level of
abstract syntax trees.

* Design goals
    :PROPERTIES:
    :CUSTOM_ID: design-goals
    :END:

Julia has been built from the ground up for scientific computing,
machine learning, data mining, large-scale linear algebra, distributed
and parallel computing.

* Articles
    :PROPERTIES:
    :CUSTOM_ID: articles
    :END:

- [[https://www.infoworld.com/article/3241107/python/julia-vs-python-julia-language-rises-for-data-science.html][Julia vs. Python: Julia language rises for data science]]
- [[https://juliacomputing.com/domains/ml-and-ai.html][Machine Learning and Artificial Intelligence]]
