----
title: Remove duplicates from Instapaper HTML export
modified: 2019-02-18
meta_description: 
tags: Computer, Software, Internet, Mobile, Web, Functional, Clojure, HTML
----

[[https://www.instapaper.com/help][Instapaper]] turns web content -- articles, stories, posts, videos, and
even long emails -- into a great reading experience.

Over the course of your day, you'll encounter things you want to save
for later. With Instapaper, you simply push a button in your browser,
or choose "send to Instapaper" in a linked mobile app. Instapaper then
saves it for you, and makes it available in a beautiful, uncluttered,
reading-optimized format on or your browser.

(.more.)

* Hickory
   :PROPERTIES:
   :CUSTOM_ID: hickory
   :END:

Hickory parses [[https://en.wikipedia.org/wiki/HTML][HTML]] into Clojure data structures, so you can analyze,
transform, and output back to HTML. HTML can be parsed into hiccup
vectors, or into a map-based DOM-like format very similar to that used
by clojure.xml. It can be used from both [[http://clojure.org/][Clojure]] and [[http://clojurescript.org/][Clojurescript]]. --
[[https://github.com/davidsantiago/hickory][Hickory]] (by *[[https://github.com/davidsantiago][David Santiago]]*)

* Duplicate links in HTML export file
   :PROPERTIES:
   :CUSTOM_ID: duplicate-links-in-html-export-file
   :END:

When adding links to Instapaper, sometimes duplicates are stored.
These will also be in an Instapaper HTML export file.

A tool (built with Hickory) to remove duplicate hyperlinks from
[[https://www.instapaper.com/][Instapaper]] HTML export files -- [[https://github.com/maridonkers/instapaper][maridonkers / instapaper]] (by *[[https://github.com/maridonkers][Mari
Donkers]]*)

* Binary download
   :PROPERTIES:
   :CUSTOM_ID: binary-download
   :END:

The ready for use binary download can be found here: [[http://photonsphere.org/downloads/instapaper.jar][instapaper.jar]]

Execute via the following command ([[https://www.java.com/][Java]] must be installed on your
machine):

#+BEGIN_SRC sh
  java -jar instapaper.jar inputfile.html outputfile.html
#+END_SRC

(Where inputfile.html is the Instapaper HTML export file, which can be
generated via Instapaper -> Settings -> Export -> Download HTML file.)
