----
title: xmonad with xterm+screen and Termonad
modified: 2021-11-15
meta_description: 
tags: Computer, Software, Linux, NixOS, Functional, Haskell, GUI, Tiling Window Manager, xmonad, Termonad
----

In the past I have used the [[https://xmonad.org/][xmonad]] tiling window manager but
eventually returned to [[https://kde.org/][KDE]], because I had some problems with truncated
text in terminal windows, needed to be able to run a complicated GUI
that was not very suited for a [[https://en.wikipedia.org/wiki/Tiling_window_manager][tiling window manager]] and I thought
there was not that much difference in performance.

(.more.)

* xmonad
    :PROPERTIES:
    :CUSTOM_ID: xmonad
    :END:

** Introduction
The documentation reads that the [[https://xmonad.org/][xmonad]] tiling window manager is fast
and configurable.

** terminal emulator
*** xterm
   The [[https://en.wikipedia.org/wiki/Xterm][xterm]] terminal emulator starts up very quickly and for me this
compensates for its lack of tabs (update: see [[#termonad][Termonad]] below).

*** text truncation
If an =xterm= window is small in size and later resized to a bigger window
the output is truncated instead of reflowed. This has always been a
big nuisance to me, but I didn't manage to find a solution earlier.

*** screen
If in the =xmonad.hs= configuration file the following code is used to
define a terminal with the =screen= command then the text in the
window is no longer truncated and reflows in a resized window.

#+BEGIN_SRC haskell
  myTerminal :: String
  myTerminal = "xterm -e \"exec screen\""

  myFloatingTerminal :: String
  myFloatingTerminal = "xterm -title \"floatterm\" -e \"exec screen\""

  --...

  keysAdditional =
      [ ("M-C-<Return>", spawn myFloatingTerminal)
      ,
      
  -- ...
    xmonad $ def {
      terminal = myTerminal,
#+END_SRC

*** detached screens
There is changed behaviour however. Because all terminals now run
automatically with a =screen= command and will continue to execute
even when killed with e.g. a =M-<Backspace>=, they can become
detached.

#+BEGIN_SRC haskell
  keysAdditional =
        [...
         , ("M-<Backspace>", kill)
#+END_SRC

With a =screen -ls= screens are listed. I have aliases to list screens
and detached screens only, and a to reattach to a detached screen.

*** aliases
The definitions for screen aliases are given below:
   #+BEGIN_SRC sh
alias r="screen -DR"
alias s="screen -ls"
alias z="screen -ls | grep '(Detached)'"
   #+END_SRC

Simply reattach to a detached screen by its listed name and use an
=exit= command or =Ctrl-D= to exit and terminate it.

** Termonad
    :PROPERTIES:
    :CUSTOM_ID: termonad
    :END:
    
Update: revisiting the [[https://github.com/cdepillabout/termonad][Termonad]] terminal emulator, which is indeed
blazingly fast and also has tabs! (Distrotube video [[https://www.youtube.com/watch?v=TLNr_gBv5HY][here]]). I'm now
using =Termonad= (again) and the above text on =xterm= only applies to
my floating terminals.

Installing vanilla =Termonad= under [[https://nixos.org/][NixOS]] from GitHub:
[[https://github.com/cdepillabout/termonad][cdepillabout/termonad]], using commands given below:

#+BEGIN_SRC sh
  mkdir -p ~/lib
  cd ~/lib
  git clone https://github.com/cdepillabout/termonad
  cd termonad
  nix-build
#+END_SRC

The build results is under the =result= subdirectory, so a symbolic
link can be created for it, as follows:

#+BEGIN_SRC sh
  mkdir -p ~/bin
  cd ~/bin
  ln -s /home/mdo/lib/termonad/result/bin/termonad
#+END_SRC

You can edit e.g. your =~/.bashrc= to add =~/bin= to your =PATH= (or
simply specify the full path in your =xmonad.hs= configuration file.

=xmonad.hs=:
#+BEGIN_SRC haskell
  myTerminal :: String
  -- myTerminal = "xterm -e \"exec screen\""
  myTerminal = "~/bin/termonad"

  myFloatingTerminal :: String
  myFloatingTerminal = "xterm -title \"floatterm\" -e \"exec screen\""
#+END_SRC

* Performance gains
My system is indeed **significantly** snappier and faster in general under
[[https://xmonad.org/][xmonad]] than it was under [[https://kde.org/][KDE]] and I now don't quite understand how I
came to a different conclusion before. It must have been
annoyance-bias over the terminal output truncate problem.

* dotfiles
    :PROPERTIES:
    :CUSTOM_ID: dotfiles
    :END:

My [[https://github.com/maridonkers/dotfiles][dotfiles]] at GitHub with a.o. [[https://github.com/maridonkers/dotfiles/tree/master/xmonadconfig][xmonad]], [[https://github.com/maridonkers/dotfiles/tree/master/.config/xmobar][xmobar]] and [[https://github.com/maridonkers/dotfiles/tree/master/.config/termonad][Termonad]] configuration.

* Already on GitHub
    :PROPERTIES:
    :CUSTOM_ID: already-on-github
    :END:

- [[https://github.com/maridonkers/nixos-configuration][NixOS configuration]]
- [[https://github.com/maridonkers/emacs-config][Emacs configuration]]
