----
title: Paperspan export (HTML) to Instapaper import (CSV) convertor
modified: 2021-10-06
meta_description: 
tags: Computer, Software, Internet, Linux, NixOS, Haskell, CSV, HTML, RegExp
----

A [[https://haskell.org][Haskell]] program to convert the [[https://www.paperspan.com][Paperspan]] HTML export format to an
[[https://instapaper.com][Instapaper]] CVS import format with automatic --configuration file
driven-- designation to folders.

(.more.)

Usage: see the [[https://github.com/maridonkers/paperspan2instapaper/blob/master/Makefile][Makefile]].

* Automatic designation to folders

Paperspan HTML export to Instapaper CSV import. With [[https://github.com/maridonkers/paperspan2instapaper/blob/master/folders-example.yaml][folders.yaml]]
configuration file, which contains Instapaper target folder names (for
output file) and [[https://github.com/niklongstone/regular-expression-cheat-sheet][regular expressions (PCRE)]] for =URL= or =text= in
Paperspan export (which is input). Each of the selectors in the
configuration file (I have hundreds) is matched against the URL or
text of the Paperspan link being imported, until a match is found and
an associated folder can be designated to it. This is very useful when
you have a lot of unorganized links in your Paperspan (which you did
not already move to a folder in).

e.g. the Paperspan link

#+BEGIN_SRC html
      <a href="https://news360.com/article/563394549"
         time_added="1630495255000">
        Stop prescribing hydroxychloroquine for Covid-19, warn researchers | Stop News – India TV
      </a>
#+END_SRC

is matched with the following selector from [[https://github.com/maridonkers/paperspan2instapaper/blob/master/folders-example.yaml][folders.yaml]]:

#+BEGIN_SRC yaml
  - "conditionRegExp": "\\bcovid-19\\b"
    "conditionSource": "text"
    "conditionFolderName": "biologyHealth"
#+END_SRC

which results in designation to the =Biology Health= folder via its
folderName (also in [[https://github.com/maridonkers/paperspan2instapaper/blob/master/folders-example.yaml][folders.yaml]]).

#+BEGIN_SRC yaml
  - "folderName": "biologyHealth"
    "folderPath": "Biology Health"
#+END_SRC

and the following CSV line is the result:

#+BEGIN_SRC csv
  https://news360.com/article/563394549,
  "Stop prescribing hydroxychloroquine for Covid-19, warn researchers | Stop News – India TV",
  https://news360.com/article/563394549,
  "Biology Health",
  1630495255000
#+END_SRC

* GitHub

  The source code for the convertor program is on GitHub:
  [[https://github.com/maridonkers/paperspan2instapaper][maridonkers/paperspan2instapaper]].

Disclaimer: this is a 'one shot' (excuse my Haskell) program that I've
used only once to import an export of my /27689/ Paperspan article
links into Instapaper.

* Earlier
  Earlier this [[https://photonsphere.org/posts/2019-02-18-instapaper-export.html][2019-02-18-instapaper-export]] was used for an Instpaper
  HTML export to Paperspan import.

  (Hopping back and forth between these excellent read-later/archiving
  solutions.)
