----
title: Webgear
modified: 2022-09-06
meta_description: 
tags: Computer, Software, Functional, Internet, Web, API, WebAPI, Haskell, Nix
----

#+OPTIONS: ^:nil

Composable, type-safe HTTP APIs in [[https://www.haskell.org/][Haskell]] -- [[https://haskell-webgear.github.io/][Webgear]] (by [[https://github.com/rkaippully][Raghu Kaippully]]).

"WebGear is a high-performance framework to build composable,
type-safe HTTP APIs. It is designed to make common API development
tasks easy. It is also easily extensible to add components needed by
your project." — [[https://github.com/haskell-webgear/webgear][haskell-webgear/webgear]]

(.more.)

* Introduction

From the [[https://haskell-webgear.github.io/][Webgear]] documentation:

"Webgear is a framework to build HTTP APIs in Haskell. WebGear helps to
run these APIs as a web application, automatically generate [[https://en.wikipedia.org/wiki/OpenAPI_Specification][OpenAPI]]
documentation, and extract other static information about the APIs in
general.

WebGear is built on a philosophy that users need not be experts on
advanced Haskell features to use a web framework. While WebGear
internally uses many advanced language extensions, considerable effort
is spent in exposing only a small portion of it in user APIs so that
you need not be an expert to use them. It also has comprehensive
documentation and examples that shortens the learning curve.

WebGear is very flexible, allowing you to build your project the way
you want. It is very easy to extend or completely replace most of the
components to make it work the way you need it to."

"Learn more about WebGear and how it compares against alternatives in the [[https://haskell-webgear.github.io/user_guide/1.0.2/index.html][user guide]]."

* Batteries Included

Authentication, validation, JSON support are all built-in.

* Why use WebGear?

Quoted directly from the [[https://haskell-webgear.github.io/user_guide/1.0.2/index.html][Webgear user guide]]:

"If you are already familiar with other Haskell web frameworks, you
might be interested in how WebGear compares against them. This section
compares WebGear against some popular frameworks to give you an idea
of why it is useful."

* Comparison against other web frameworks

Detailed [[https://haskell-webgear.github.io/user_guide/1.0.2/index.html][comparison]] — Webgear ([[https://github.com/haskell-webgear/webgear][haskell-webgear/webgear]]) compared
against Servant ([[https://github.com/haskell-servant/servant][haskell-servant/servant]]), IHP ([[https://github.com/digitallyinduced/ihp][digitallyinduced/ihp]]),
Scotty ([[https://github.com/scotty-web/scotty][scotty-web/scotty]]).

* Examples

Examples of WebGear applications can be found at:

- • [[https://github.com/haskell-webgear/webgear-example-hello][Hello World]]
- • [[https://github.com/haskell-webgear/webgear-example-users][A basic CRUD app that operates on user resources]]
- • [[https://github.com/haskell-webgear/webgear-example-realworld][Realworld — a medium.com clone (called conduit)]]
